services:
    app:
        basedir: app
        environment:
            DEBUG: True
            SOME_VAR: "it works on ma machine"
        build:
            - virtualenv venv
            - ./venv/bin/pip install -r requirements.txt
            - echo $SOME_VAR
        run:
            - ./venv/bin/python example.py
        depends_on:
            - otoapp
        test:
            - py.test

    otoapp:
        basedir: .
