services:
    app:
        basedir: ./
        environment:
            DEBUG: True
        build:
            - pipenv install -r requirements.txt --python 3.6.3
        run:
            - python manage.py runserver
        depends_on:
            - otoapp
        test:
            - py.test

    oto app:
